image: nixos/unstable

packages:
  - nixos.cachix

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  repo: "nix-config"
  cachix: "nix-action"
  nur: "misterio"

secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af

tasks:
- setup_cachix: |
    cachix authtoken --stdin < ~/.cachix_token
    cachix use "$cachix"
- build: |
    cd "$repo"
    my_packages="$(eval echo .#{$(nix eval --raw --file ./pkgs --apply 'f: builtins.concatStringsSep "," (builtins.attrNames (f { } ))')})"
    nix build $my_packages .#deploy-rs.deploy-rs
- upload_cachix: |
    nix path-info "$repo"/result*/ -r | cachix push "$cachix"
- update_nur: |
    curl -XPOST "https://nur-update.herokuapp.com/update?repo=${nur}"
