[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = ["./pkgs/_sources/*"]

[formatter.prettier]
command = "prettier"
options = ["--plugin", "prettier-plugin-toml", "--write"]
includes = ["*.css", "*.html", "*.js", "*.json", "*.jsx", "*.md", "*.mdx", "*.scss", "*.toml", "*.ts", "*.yaml", "*.yml"]
excludes = ["./pkgs/_sources/*"]

[formatter.shell]
command = "shfmt"
options = ["-bn", "-ci", "-sr", "-i", "2", "-s", "-w"]
includes = ["*.sh", "*.zsh"]
