# nvfetcher.toml
[dnsmasq-china-list]
src.git = "https://github.com/felixonmars/dnsmasq-china-list"
fetch.github = "felixonmars/dnsmasq-china-list"

[fcitx5-material-color]
src.git = "https://github.com/hosxy/Fcitx5-Material-Color"
fetch.github = "hosxy/Fcitx5-Material-Color"

[fcitx5-pinyin-moegirl]
src.git = "https://github.com/outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict.yaml"

[fcitx5-pinyin-zhwiki]
src.git = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki"
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230128.dict.yaml"

[gfwlist]
src.git = "https://github.com/gfwlist/gfwlist"
fetch.github = "gfwlist/gfwlist"
