# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    cleanTmpDir = true;
    # extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
    extraModulePackages = [ ];
    initrd = {
      availableKernelModules = [ "uhci_hcd" "ata_piix" "firewire_ohci" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "wl" ];
    kernelPackages = pkgs.linuxPackages_latest;
    supportedFilesystems = [ "btrfs" "exfat" "ntfs" "vfat" ];
    tmpOnTmpfs = true;
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/root";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };
    "/nix" = {
      device = "/dev/disk/by-label/nix";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };
    "/home" = {
      device = "/dev/disk/by-label/home";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };
  };

  swapDevices = [{ device = "/swapfile"; size = 6*1024; }];

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking = {
    enableB43Firmware = true;
    hostName = "d630";
    useDHCP = lib.mkDefault false;
    interfaces = {
      enp9s0.useDHCP = lib.mkDefault true;
      wlan0.useDHCP = lib.mkDefault true;
    };
  };

  # use cpupower
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
