# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dnsmasq-china-list = {
    pname = "dnsmasq-china-list";
    version = "1be2bbbfc63ae08ae838a84595b02dea4938535c";
    src = fetchFromGitHub {
      owner = "felixonmars";
      repo = "dnsmasq-china-list";
      rev = "1be2bbbfc63ae08ae838a84595b02dea4938535c";
      fetchSubmodules = false;
      sha256 = "sha256-udgCgfEAcn5rsaZkbmyyNMSsTWigS0mJqTccnjrJpAg=";
    };
    date = "2023-07-29";
  };
  fcitx5-material-color = {
    pname = "fcitx5-material-color";
    version = "2256feeae48dcc87f19a3cfe98f171862f8fcace";
    src = fetchFromGitHub {
      owner = "hosxy";
      repo = "Fcitx5-Material-Color";
      rev = "2256feeae48dcc87f19a3cfe98f171862f8fcace";
      fetchSubmodules = false;
      sha256 = "sha256-i9JHIJ+cHLTBZUNzj9Ujl3LIdkCllTWpO1Ta4OT1LTc=";
    };
    date = "2021-02-21";
  };
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "45a8103afd12a1decca35dce2f076f4f5b8cdc59";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20230414/moegirl.dict.yaml";
      sha256 = "sha256-0hDjF1/Gt+OU6/YEY+t1efIRWpqPrKIiaMRBQ0zEWJg=";
    };
    date = "2022-09-24";
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "0964bd8438380d96ea2987eafd7e82926eeaa0a0";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20230329.dict.yaml";
      sha256 = "sha256-0B02FGISHqvrBUGkERdplhrx8zo6SV9hG2qRbSUqqd0=";
    };
    date = "2023-07-28";
  };
  gfwlist = {
    pname = "gfwlist";
    version = "412d67356a83e6e35735c0d9ff4b491d32f7d097";
    src = fetchFromGitHub {
      owner = "gfwlist";
      repo = "gfwlist";
      rev = "412d67356a83e6e35735c0d9ff4b491d32f7d097";
      fetchSubmodules = false;
      sha256 = "sha256-5bW5tpJmsRjdNW/DtomM9jpYPNXe8xSMLJCgvX3lgOI=";
    };
    date = "2023-07-23";
  };
}
