name: "Check Syntax"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - slug: Check Syntax
            job_name: Checking
            nix-command: flake check
    name: ${{ matrix.slug }}
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            keep-going = true
            show-trace = true
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: nix-actions
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          extraPullNames: nix-community,nix-on-droid
      - name: ${{ matrix.job_name }}
        uses: nick-invision/retry@v2.8.3
        with:
          max_attempts: 2
          timeout_minutes: 720
          retry_on: error
          command: |
            nix \
              --log-format bar-with-logs \
              ${{ matrix.nix-command }}
