name: Build and test flake outputs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        system:
          - aarch64
          - x86_64
        nix-command:
          - flake check
        include:
          - nix-command: build -L --keep-going .#homeConfigurations.actoriu.activationPackage
            system: x86_64
          - nix-command: build -L --keep-going .#nixosConfigurations.d630.config.system.build.toplevel
            system: x86_64
          - nix-command: build -L --keep-going .#nixOnDroidConfigurations.oneplus5.activationPackage --impure
            system: aarch64
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: docker/setup-qemu-action@v2
        if: ${{ matrix.system == 'aarch64' }}
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = aarch64-linux
            experimental-features = nix-command flakes recursive-nix
      - uses: cachix/cachix-action@v10
        with:
          name: actoriu
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: actoriu,nix-community,nix-on-droid
      #- uses: nick-invision/retry@v2.7.0
      #  with:
      #    max_attempts: 2
      #    timeout_minutes: 5
      #    retry_on: error
         run: |
            cachix watch-exec nix-config -- \
              nix \
                ${{ matrix.nix-command }}

