name: "Updates flake.lock"

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - flake.nix

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Generate token
        uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.APP_ID }}"
          private_key: "${{ secrets.APP_PRIVATE_KEY }}"
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        id: update-flake-lock
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          pr-title: "chore(deps): flake.lock update"
          commit-msg: "chore(deps): flake lock update"
          git-author-name: "github-actions[bot]"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-name: "github-actions[bot]"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
      - name: Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          pull-request-number: "${{ steps.update-flake-lock.outputs.pull-request-number }}"
          merge-method: squash
