name: Format code

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Formatter
        run: nix fmt
