name: Use nvfetcher update package

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-pkgs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - slug: Update package
            job_name: Use nvfetcher update package
            nix-command: develop -c nvfetcher
    name: ${{ matrix.slug }}
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]@users.noreply.github.com"
      - name: Update package
        run: |
          nix develop -c nvfetcher
          if [ -z "$(git status --porcelain)" ]; then
            echo "repository is clean, skip commit"
          else
            git add --all
            git commit -m "update packages."
          fi
      - name: Git push
        run: |
          git push origin main
