name: "Update flake.lock"

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - flake.nix

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - slug: Update flake.lock
            job_name: Updating
            nix-command: |
              --option commit-lockfile-summary "flake: bump inputs" \
              flake update --commit-lock-file
    name: ${{ matrix.slug }}
    steps:
      - name: Set swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Install nix
        uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: ${{ matrix.job_name }}
        uses: nick-invision/retry@v2.8.3
        with:
          max_attempts: 2
          timeout_minutes: 720
          retry_on: error
          command: |
            nix \
              --log-format bar-with-logs \
              ${{ matrix.nix-command }}
      - name: Push changes to main
        run: git pull --rebase --autostash && git push
